### ISSUE TITLE
https:// site is broken (cert issue)

### ISSUE THREAD

**Issue by nchammas** [HypothesisWorks/HypothesisWorks.github.io#13]
http://hypothesis.works/ works fine for me, but visiting https://hypothesis.works/ in Chrome yields a scary warning. If I ignore the warning and proceed anyway, I get a site with broken styling:

![screen shot 2016-11-16 at 6 59 11 pm](https://cloud.githubusercontent.com/assets/1039369/20370826/d287b654-ac2e-11e6-97a2-f8ffce5e0b72.png)

**Comment by DRMacIver** [comment]
Thanks for reporting this. 

There's not a huge amount I can do about it at the moment (except maybe stick cloudflare in front of it and mask the issue) - it's mostly down to HTTPS support for custom domains on github pages. I'll keep an eye on whether things improve though.

**Comment by nchammas** [comment]
This no longer appears to be an issue. https://hypothesis.works/ now works as expected.
