### ISSUE TITLE
How to submit a new article for the site?

### ISSUE THREAD

**Issue by hwayne** [HypothesisWorks/HypothesisWorks.github.io#29]
I want to submit this: https://gist.github.com/hwayne/93688c0ded97b6b4d802411028db5e21, been working with @Zac-HD but neither of us knows the flow for contributing guest articles

**Comment by Zac-HD** [comment]
I think you add yourself to https://github.com/HypothesisWorks/HypothesisWorks.github.io/blob/master/_data/authors.yml and drop the markdown file in https://github.com/HypothesisWorks/HypothesisWorks.github.io/tree/master/_posts, but @DRMacIver or maybe @alexwlchan will actually know.

**Comment by alexwlchan** [comment]
Yeah, I think that’s what I did

I’d be happy to review as well, but David has final say on what gets posted.

**Comment by hwayne** [comment]
Submitted
