### ISSUE TITLE
The newsletter signup does not work correctly

### ISSUE THREAD

**Issue by eivindjahren** [HypothesisWorks/HypothesisWorks.github.io#35]
After following the link in the newsletter signup I get sent to the mailchimp pricing plan.

https://github.com/HypothesisWorks/HypothesisWorks.github.io/blob/f1c0bb5004151f9d980d7f5a1121e13875f04d74/index.md?plain=1#L70

**Comment by Zac-HD** [comment]
See https://github.com/HypothesisWorks/hypothesis/issues/2943 - we know the website is out of date, and just haven't finished fixing it yet 😞
